### ISSUE TITLE
Decoupling Interfaces for End-chains and Khalani Chain into Independent Packages

### ISSUE THREAD

**Issue by Defcon023** [tvl-labs/khalani-core#186]
## Description
Currently, the interfaces for the end-chains and Khalani chain are tightly coupled within the same package, making it difficult to achieve a clean separation of concerns. To improve modularity and code maintainability, we propose decoupling these interfaces into two independent packages that cannot directly import each other, except for the shared interfaces.

**Comment by samtvlabs** [comment]
@Defcon023 is this still something we need to contend with given the current status of the code base?
